### ISSUE TITLE
Error "subscriptionType" on introspection query

### ISSUE THREAD

**Issue by maggo** [clayallsopp/graphqlhub#10]
I'm currently trying to follow your [Relay tutorial](https://medium.com/@clayallsopp/relay-101-building-a-hacker-news-client-bb8b2bdc76e6#.pxhf26hcn) but using updated dependencies. When I implement the babel plugin and tell it to do an introspectionQuery on https://www.graphqlhub.com/graphql I get an error `Cannot query field "subscriptionType" on "__Schema".`

**Comment by clayallsopp** [comment]
@maggo can you try now?

**Comment by maggo** [comment]
Works! Thank you!
