### ISSUE TITLE
Feature request: a really complicated schema

### ISSUE THREAD

**Issue by mattkrick** [clayallsopp/graphqlhub#9]
Love the repo!
I'm looking for a schema that has all the tough stuff included. For example, something with:
- Unions
- Interfaces
- Pagination
- Nested pagination (eg get first 5 blog posts after cursor & last 5 comments for each sorted by time)
- Circular reference pagination (eg most recent 5 books with `inStock: true`, show first 3 authors of each book, for each author show 5 most popular books)
- Pagination where each result is a union type
- ? Whatever else the community can think up

Underlying data isn't important, but it'd be nice to have a single place to get a little refresher on how I should shape my data when I'm building something.

Happy to help where I can!

**Comment by clayallsopp** [comment]
@mattkrick definitely - I actually thing GraphQL'izing the Facebook API might be a reasonable way to show all those?

maybe less ambitiously, the current Github implementation is relatively barebones, partly to avoid implementing more complex things like pagination (i.e. comments pagination, commits pagination, etc)

would love to see a contribution along those lines - Relay has [good examples](https://facebook.github.io/relay/docs/graphql-connections.html#content) on pagination and more complex schemas, which might be good to mirror

**Comment by clayallsopp** [comment]
@mattkrick check out this: https://www.graphqlhub.com/playground?query=%23%20Welcome%20to%20GraphQLHub!%20Type%20your%20GraphQL%20query%20here%2C%20or%0A%23%20explore%20the%20%22Docs%22%20to%20the%20right%0A%0A%7B%0A%20%20hn2%20%7B%0A%20%20%20%20nodeFromHnId(id%3A%22rdl%22%2C%20isUserId%3Atrue)%20%7B%0A%20%20%20%20%20%20...%20on%20HackerNewsV2User%20%7B%0A%20%20%20%20%20%20%20%20submitted(first%3A%205)%20%7B%0A%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20HackerNewsV2Story%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hnId%0A%09%09%09%09%09%09%09%09score%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20url%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20title%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20HackerNewsV2Comment%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20text%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20kids(first%3A%202)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09text%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20by%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09hnId%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20by%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20hnId%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20submitted(first%3A2)%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20...%20on%20HackerNewsV2Comment%20%7B%0A%09%09%09%09%09%09%09%09%09%09%09%09%09text%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%09%09%09%09%09%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

it has everything from your comment (pagination, circular references, interfaces) except union types. added in #28 and #29

**Comment by mattkrick** [comment]
oh that is awesome! i can't imagine a practical use for nested pagination, but there it is! all we need now are some inline fragments inside some fragment spreads (or unions) & we've got the perfect playground for folks to build query tools with!
